# -*- coding: utf-8 -*-
"""My Python BAsics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11hhZxU3oTYYEzMoMZelS9KyUzjZNzoZT
"""

#day1
print("Suresh")
print("Suresh","Xavier")
print('''Jesus
Christ''')
print('Hello','World',sep='_',end ='\t' )
print("SureshXavier")
print('Suresh' * 3)
print('Benita' + 'Pushpam')

#day2 #datatypes
a='Xavier'
b=67
c=8.98
print(type(a))
print(type(b))
print(type(c))

#input functions
Data=int(input("Enter the Digit"))
print(Data)
print(type(Data))
print(Data*5)

#day3
#arithmetic operators
x=int(input("enter a number:"))
y=int(input("enter the another number"))
print(x+y)
a=int(input("Enter a number:"))
b=float(input("enter the another number:"))
print(a/b)
print(a//b)
d=int(input("Enter a number:"))
E=int(input("Enter the another number:"))
print(d%E)

#boolean datatypes
#relational operators
a=89
b=98
a==b

#augmented assignment operations
a=9
a+=3
print(a)
b=8
b-=4
print(b)
c=2
c*=4
print(c)
d=3
d//=1
print(d)

#logical operators
#and
b=True and True
print(b)
a=(10>2)and(67<68)
print(a)

#or
a=False or False
print(a)
b=True or False
print(b)

#not
a=not True
b=not False
print(a,b)

from ast import NotEq
#conditional statements
#if else statements
a=54 
b=22
if a>b:
  print('Larger')
elif a==b:
  print("Larger or Smaller")
else:
  print('Smaller')

#loops
#for loop
for i in range(0,10,2):
  print(i)

#while
a=1
while a<10:
  print(a)
  a+=1

#Quiz 1
a=int(input("Enter a number"))
for i in range(a):
  print(i,end='')

#jump statements
#continue
for i in range(0,10):
  if i == 7:
    continue
  print(i)

#break
for i in range(0,10):
  if i == 8:
    break
  print(i)

print('Xavier')

#else clause
while i >=72:
  if i==19:
    break
  print(i)
else:
   print('I')

#lists
list=['xavier','beni','sathya']
print(list[2])
print(list[-1])

#mutability
#traversal
list=['xavier','sures','beni']
for i in list:
  print(i)

#quiz
lst=[10,30,40,60]
print((10*2)in lst)
print(lst[-1]+lst[1])

#list functions
#length of the list#maximum #minimum
list=[1,2,3,4]
print(len(list))
print(max(list))
print(min(list))

#to add in list #append
list=[1,2,34,45]
list.append(98)
print(list)

#insert
list=['xavier','suresh','print','tata']
list.insert(0,0)
print(list)

#extend
list=['revi','sevi','dibi','givi']
list.extend(['fifi','hihi','vivi'])
print(list)
type (list[3])

#remove
list=[1,2,3,1]
list.remove(1)
print(list)

#pop
list=[1,2,3,4,5,6,]
element=list.pop(5)
print(list)
print(element)

#sort ascending order
list=[789,656,9999,7856,1,675,6,98,665,5,2,3,4,]
list.sort()
print(list)

#descending order
list=[789,656,9999,7856,1,675,6,98,665,5,2,3,4,]
list.sort(reverse=True)
print(list)

lst=list('Trol Geek')
print(lst)

#quuiz
Lst=[10,50]
Lst.append(87)
Lst.extend([89,98,8,77,34])
print(Lst)

#immutable datatype
tup=(1,2,3)
print(tup[2])
print(tup[-2])

a=tuple('Xavier Suresh')
print(a)
print(type(a))

a=tuple([9,8,7])
print(a)
print(type(a))

a=(23,)
print(a)
type(a)

a= (1,2,3)
for i in a:
  print(i)

#string,list,tuple slicing
a=('Suresh Xavier')
print(a[0:4])

a=('Suresh Xavier')
print(len(a))
print(a[0:25])

a=('Suresh Xavier')
print(a[0:5:2])